// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzpVuA-_4g3Da49CH0oYLPmDNy1M1mrE8',
    appId: '1:266676887884:web:31aeb3f20793ec08502fe9',
    messagingSenderId: '266676887884',
    projectId: 'shop-666b8',
    authDomain: 'shop-666b8.firebaseapp.com',
    databaseURL: 'https://shop-666b8-default-rtdb.firebaseio.com',
    storageBucket: 'shop-666b8.firebasestorage.app',
    measurementId: 'G-W9F0FJD8FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAelgF6Aq92ONFja7tafpWxDG7EEdFRYs',
    appId: '1:266676887884:android:dc0955d39f1815fc502fe9',
    messagingSenderId: '266676887884',
    projectId: 'shop-666b8',
    databaseURL: 'https://shop-666b8-default-rtdb.firebaseio.com',
    storageBucket: 'shop-666b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKaqtNISn_4g9CdywBfQBhSoxhnGvB2jI',
    appId: '1:266676887884:ios:49cc61c8381a68ab502fe9',
    messagingSenderId: '266676887884',
    projectId: 'shop-666b8',
    databaseURL: 'https://shop-666b8-default-rtdb.firebaseio.com',
    storageBucket: 'shop-666b8.firebasestorage.app',
    androidClientId: '266676887884-5k7skmeb3vktngu1ij6lhnrdnk8omgvv.apps.googleusercontent.com',
    iosClientId: '266676887884-mpoaha84ja9klj2p8qbuvbubu7637oen.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKaqtNISn_4g9CdywBfQBhSoxhnGvB2jI',
    appId: '1:266676887884:ios:49cc61c8381a68ab502fe9',
    messagingSenderId: '266676887884',
    projectId: 'shop-666b8',
    databaseURL: 'https://shop-666b8-default-rtdb.firebaseio.com',
    storageBucket: 'shop-666b8.firebasestorage.app',
    androidClientId: '266676887884-5k7skmeb3vktngu1ij6lhnrdnk8omgvv.apps.googleusercontent.com',
    iosClientId: '266676887884-mpoaha84ja9klj2p8qbuvbubu7637oen.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzpVuA-_4g3Da49CH0oYLPmDNy1M1mrE8',
    appId: '1:266676887884:web:0c4c2293f425852f502fe9',
    messagingSenderId: '266676887884',
    projectId: 'shop-666b8',
    authDomain: 'shop-666b8.firebaseapp.com',
    databaseURL: 'https://shop-666b8-default-rtdb.firebaseio.com',
    storageBucket: 'shop-666b8.firebasestorage.app',
    measurementId: 'G-E23S2P1KQZ',
  );

}